{% set name = "pygff" %}
{% set version = "1.1.0" %}
{% set sha256 = "d242a541ed6829fa855111262c4bcdcc87fb21c4ee8e9637be759e54af2c27b7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - numpy
    - pandas >0.23.*
  run:
    - python >=3
    - {{ pin_compatible('numpy') }}
    - pandas >0.23.*

test:
  imports:
    - pygff

about:
  home: https://github.com/betteridiot/pygff
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: GFF3 reader designed for educational use at the University of Michigan, Department of Computational Medicine & Bioinformatics

extra:
  recipe-maintainers:
    - betteridiot
