travis:
  secure:
    BINSTAR_TOKEN: XPPnVJKxreBYsvmGCNseL2ltYhg+g1ADzMSkn/FCCJj+or/dN0K3eGtk7axqdP8lobxhzHmBUDfd1eg9ZiRioba54JKB6KQ2yCaCU/33dY0afxofV4V0ZKcefgTIfTu3IKpXzX7W39boMYtqDfzNiOHAtaBtwHv90j64APawivdGJhlPoyBaf+m9cf7p7D1R8JpzzVlZgAK3pJAjIrI6ymZs8w3NKcGu3ANORkoVRbPpDQJVOugFfESNyMc0eBQxXO21HzF+TyMRdvRdI62K5lb2mMtSqhTl89NX0GLQLXBgcwbuqVwILb0pMCtrgtwCD0xHKZ9mp/cGPzMgxniUJn82eIPy7xI9dN/6os0i3EBe4XhkxOgsmAcI7k2RfU6QSiCM/ubnLRSO2NtDqAA17FT+Qf4t2ymU47wEuK8Ibi4XDZOuDEYHWoeGBUKs7AW6ayvrfj460xOvNrjO/v4jIsMXQPCJ570XczJP/ba2MUzrl+u79MjL69IA+0+2IJVyPdn3ON9ZX2krS9zMhXpfNviZITPtN4B8Jf0vR0vpzpchGTjx3pm9yCWnpZlGwQ05aHeDWwy6mTR73GoQfGqzQZ/Vt2tMIilNBrq12Z2BJApczdY33ddYH7/V6UA8o3aVb7JxQxPQE97g1ogBG/jeAOR4Vd2zqeRKpIdUQNeZoFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
